//! Neutral syscall numbering.
//!
//! The kernel speaks in per-ABI numbers; internally everything is keyed by the
//! `Sysnum` enum.  Tables are generated by `build.rs` from `data/`.

use crate::Word;
use crate::arch::SYSCALL_AVOIDER;

include!(concat!(env!("OUT_DIR"), "/sysnums.rs"));

/// Guest ABI of a tracee (see `tracee::abi`).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Abi {
    Default = 0,
    /// x86_32 on x86_64 (ARM EABI on AArch64).
    Abi2 = 1,
    /// x32 on x86_64.
    Abi3 = 2,
}

struct Sysnums {
    table: &'static [Sysnum],
    offset: Word,
}

fn get_sysnums(abi: Abi) -> Sysnums {
    match abi {
        Abi::Default => Sysnums {
            table: &SYSNUMS_X86_64,
            offset: 0,
        },
        Abi::Abi2 => Sysnums {
            table: &SYSNUMS_I386,
            offset: 0,
        },
        Abi::Abi3 => Sysnums {
            table: &SYSNUMS_X32,
            offset: 0x4000_0000,
        },
    }
}

/// Translate an architecture-specific syscall number to a neutral `Sysnum`;
/// `Sysnum::Void` for out-of-range or unmapped numbers.
pub fn translate_sysnum(abi: Abi, sysnum: Word) -> Sysnum {
    let sysnums = get_sysnums(abi);
    if sysnum < sysnums.offset {
        return Sysnum::Void;
    }
    let index = (sysnum - sysnums.offset) as usize;
    if index >= sysnums.table.len() {
        return Sysnum::Void;
    }
    sysnums.table[index]
}

/// Translate a neutral `Sysnum` back to the architecture number for @abi;
/// `SYSCALL_AVOIDER` when the syscall does not exist for that ABI.
pub fn detranslate_sysnum(abi: Abi, sysnum: Sysnum) -> Word {
    if sysnum == Sysnum::Void {
        return SYSCALL_AVOIDER;
    }
    let sysnums = get_sysnums(abi);
    for (i, &s) in sysnums.table.iter().enumerate() {
        if s == sysnum {
            return i as Word + sysnums.offset;
        }
    }
    SYSCALL_AVOIDER
}
